### ISSUE TITLE
Move Images out of Imagur and Into Repo

### ISSUE THREAD

**Issue by gh0stwheel** [radicle-dev/radicle-drips-docs#6]
The technical-overview.md page in v2 contains references to a number of image files that Manuel originally hosted on Imagur. @CodeSandwich has pointed out that it probably makes more sense to move these into the website/ dir and host them locally to the docs pages.

**Comment by CodeSandwich** [comment]
Fixed in https://github.com/radicle-dev/radicle-drips-docs/pull/11.
